"""create spatial tables

Revision ID: 3a1a881a33fb
Revises: 
Create Date: 2026-03-20 16:43:34.831452
"""
from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a1a881a33fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.create_table('burns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_geom', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('county', sa.String(), nullable=False),
    sa.Column('burn_date', sa.Date(), nullable=False),
    sa.Column('acreage', sa.Float(), nullable=False),
    sa.Column('objective', sa.String(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('location_geom', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('site_name', sa.String(), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    op.create_table('burn_window_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('burn_id', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('recommendation', sa.String(), nullable=False),
    sa.Column('source', sa.String(), server_default=sa.text("'ml'"), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='ck_burn_window_scores_score_range'),
    sa.ForeignKeyConstraint(['burn_id'], ['burns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_burn_window_scores_burn_id'), 'burn_window_scores', ['burn_id'], unique=False)
    op.create_index(op.f('ix_burn_window_scores_timestamp'), 'burn_window_scores', ['timestamp'], unique=False)
    op.create_table('net_positive_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('burn_id', sa.Integer(), nullable=False),
    sa.Column('co2_prevented', sa.Float(), nullable=False),
    sa.Column('prescribed_emissions', sa.Float(), nullable=False),
    sa.Column('wildfire_baseline_emissions', sa.Float(), nullable=False),
    sa.Column('biodiversity_gain_index', sa.Float(), nullable=False),
    sa.Column('fuel_load_reduction_pct', sa.Float(), nullable=False),
    sa.Column('vegetation_recovery_curve', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['burn_id'], ['burns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_net_positive_metrics_burn_id'), 'net_positive_metrics', ['burn_id'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('soil_moisture', sa.Float(), nullable=False),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_readings_sensor_id'), 'sensor_readings', ['sensor_id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_timestamp'), 'sensor_readings', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_readings_timestamp'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_sensor_id'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_net_positive_metrics_burn_id'), table_name='net_positive_metrics')
    op.drop_table('net_positive_metrics')
    op.drop_index(op.f('ix_burn_window_scores_timestamp'), table_name='burn_window_scores')
    op.drop_index(op.f('ix_burn_window_scores_burn_id'), table_name='burn_window_scores')
    op.drop_table('burn_window_scores')
    op.drop_table('sensor_nodes')
    op.drop_table('burns')
    # ### end Alembic commands ###
